### ISSUE TITLE
Artifact removal

### ISSUE THREAD

**Issue by nakosung** [dsanno/chainer-dfi#1]
According to paper, they had implemented two kinds of artifact removal techniques.

1. Similar color distribution
2. Compensate with original image's residual 

Any plans to implement this feature?

**Comment by dsanno** [comment]
Hi.

I implemented both artifact removal techniques.
Regarding using image's residual, well reconstruction of original image has little distortion and its residual doesn't work, so I used residual of incompletely reconstructed image that has some distortion.
